title: Dou Mao

name: Doumao's homepage
description:  good good study，day day up.
url: http://doumaomao.github.io

# 自定义post url
permalink: /blog/:title.html
timezone: Asia/Chongqing

# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false

markdown: kramdown
toc_levels: 1..2
kramdown:
    input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
    extensions:
    - autolink
    - footnotes
    - smart
hard_wrap: false
#  use_coderay: true
syntax_highlighter: rouge
#  coderay:
#  coderay_line_numbers:  nil

# White-listed plugins
gems:
  - jekyll-sitemap
