markdown: rdiscount
permalink: /:title/
url: http://doumaomao.github.io/
#highlighter: pygments
pygments: true
name: doumaomao
description: doumaomao | day day up
author: doumaomao
email: 07068002@163.com
duoshuo: doumaomao
weibo: 洁小瑜
hub: doumaomao
safe: true
paginate: 100
about: "持续成长，心情愉悦"
